title: My Blog
theme: minima
author: constanteof09
email: lavipastrana@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple blog where I talk about stuff I like: programming, art, music, and games.  
  
# social links
twitter_username: notwitter # DO NOT include the @ character, or else the build will fail!
github_username:  constanteof09 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
